{
 "title": "BC-IAD",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average capital amount",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(bc_iad_capital_movement[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bc_iad_failed_transactions_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 5m failed transations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(bc_iad_failed_transactions_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "transaction response time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(bc_iad_transaction_response_time_seconds_sum[5m]) / rate(bc_iad_transaction_response_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(bc_iad_transactions_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(bc_iad_transaction_response_time_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 20s number of transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(bc_iad_transactions_total[20s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}