services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s3cret
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

  mongo-client:
    image: mongoclient/mongoclient
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://root:s3cret@mongo:27017/test?authSource=admin&useUnifiedTopology=true&useNewUrlParser=true
    ports:
      - 3005:3000
    depends_on:
      - mongo

  mongo-exporter:
    image: bitnami/mongodb-exporter
    environment:
      - MONGODB_URL=mongodb://root:s3cret@mongo:27017/test?authSource=admin&useUnifiedTopology=true&useNewUrlParser=true
volumes:
  mongo:
