global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: 'bc-iad'
    metrics_path: /metrics
    static_configs:
      - targets: ['bc-iad:3000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
