global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: 'bc-iad'
    metrics_path: /metrics
    static_configs:
      - targets: ['bc-iad:3000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'blackbox-bc-iad'
    metrics_path: /probe
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
    static_configs:
      - targets: [http://bc-iad:3000/healthcheck]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: blackbox-exporter # To get metrics about the exporter itself
    metrics_path: /metrics
    static_configs:
      - targets: [blackbox:9115]
