@uri=http://localhost:3000

###
# @name TransactionList
GET {{uri}}/transactions

###
# @name Metrics
GET {{uri}}/metrics 

###
# @name TransactionList
POST {{uri}}/transactions
Content-Type: application/json

{
    "amount":1200,
    "type":"bonifico"
}

###
# @name Healthcheck
GET {{uri}}/healthcheck 